name: CICD pipeline view

on:
  push:
    branches: ["main"]

jobs:
  compile:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
        
      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Node App
        run: |
          node app.js &
          sleep 10
          curl http://localhost:3000
     
     
    
          

      
        
     
